version: "3.8"

services:
  frontend:
    image: valamuri/notes2anki-frontend:latest
    container_name: notes2anki-frontend
    restart: always
    expose:
      - "3000"

  backend:
    image: valamuri/notes2anki-backend:latest
    container_name: notes2anki-backend
    restart: always
    expose:
      - "8000"
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      # TODO: fill out the details
    command: sh -c 'certbot certonly --webroot -w /var/www/certbot -d yourdomain.com -d www.yourdomain.com --email your_email@example.com --agree-tos --no-interactive' # Your domain & email
