[project]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Vivek Alamuri",email = "valamuri@uwaterloo.ca"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py (==2.3.2)",
    "python-dotenv (==1.0.0)",
    "aiohttp (==3.9.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
