[tool.poetry]
name = "notes2anki"
version = "0.1.0"
description = ""
authors = ["Vivek Alamuri <valamuri@uwaterloo.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
genanki = "^0.13.1"
docling = "^2.24.0"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
cohere = "^5.13.12"
python-multipart = "^0.0.20"
python-dotenv = "^1.0.1"
google-genai = "^1.2.0"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.1.1"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
