version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes2anki-frontend
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000" # Expose directly for local
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_MAX_FILES=5
      - NEXT_PUBLIC_MAX_FILE_SIZE=15 # in MB

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes2anki-backend
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000" # Expose directly for local

volumes:
  certbot-etc: # These volumes are still defined for consistency, even if not used locally
  certbot-var:
  certbot-www:
